form_generator_form_homepage:
    path:     /
    defaults: { _controller: FormGeneratorFormBundle:Default:index }

form_generator_form_afficherTopic:
    path:     /topic/{id}
    defaults: { _controller: FormGeneratorFormBundle:Default:afficherTopic }
    requirements:
        id: '\d+'

form_generator_form_createTopic:
    path:     /createtopic
    defaults: { _controller: FormGeneratorFormBundle:Default:createTopic }

form_generator_form_allResults:
    path:     /allresults/{id}
    defaults: { _controller: FormGeneratorFormBundle:Default:allresultsTopic }
    requirements:
        id: '\d+'