form_generator_form_homepage:
    path:     /
    defaults: { _controller: FormGeneratorFormBundle:Default:index }

form_generator_form_addQuestion:
    path:     /test
    defaults: { _controller: FormGeneratorFormBundle:Default:addQuestion }