form_generator_form:
    resource: "@FormGeneratorFormBundle/Resources/config/routing.yml"
    prefix:   /form
app:
    resource: '@AppBundle/Controller/'
    type: annotation
login:
    path: /login
homepage:
    path:     /
    defaults: { _controller: FormGeneratorFormBundle:Default:index }